interface SleeperStatsEntry {
    [key: string]: number;
    // yds_allow_400_449: SleeperStatValue;
    // yds_allow_550p: SleeperStatValue;
    // yds_allow_100_199: SleeperStatValue;
    // pass_2pt: SleeperStatValue;
    // pass_int: SleeperStatValue;
    // fgmiss: SleeperStatValue;
    // fgmiss_50p: SleeperStatValue;
    // rec_yd: SleeperStatValue;
    // xpmiss: SleeperStatValue;
    // def_pr_td: SleeperStatValue;
    // fgm_30_39: SleeperStatValue;
    // yds_allow_450_499: SleeperStatValue;
    // blk_kick: SleeperStatValue;
    // pts_allow_7_13: SleeperStatValue;
    // ff: SleeperStatValue;
    // fgm_20_29: SleeperStatValue;
    // fgm_40_49: SleeperStatValue;
    // pts_allow_1_6: SleeperStatValue;
    // yds_allow_300_349: SleeperStatValue;
    // st_fum_rec: SleeperStatValue;
    // def_pass_def: SleeperStatValue;
    // yds_allow_500_549: SleeperStatValue;
    // def_st_ff: SleeperStatValue;
    // st_ff: SleeperStatValue;
    // yds_allow_0_100: SleeperStatValue;
    // yds_allow_350_399: SleeperStatValue;
    // pts_allow_28_34: SleeperStatValue;
    // fgm_50p: SleeperStatValue;
    // fum_rec: SleeperStatValue;
    // def_td: SleeperStatValue;
    // fgm_0_19: SleeperStatValue;
    // int: SleeperStatValue;
    // pts_allow_0: SleeperStatValue;
    // pts_allow_21_27: SleeperStatValue;
    // rec_2pt: SleeperStatValue;
    // rec: SleeperStatValue;
    // fgmiss_30_39: SleeperStatValue;
    // xpm: SleeperStatValue;
    // st_td: SleeperStatValue;
    // def_st_fum_rec: SleeperStatValue;
    // def_st_td: SleeperStatValue;
    // sack: SleeperStatValue;
    // fgm: SleeperStatValue;
    // rush_2pt: SleeperStatValue;
    // fgmiss_40_49: SleeperStatValue;
    // rec_td: SleeperStatValue;
    // pts_allow_35p: SleeperStatValue;
    // pts_allow_14_20: SleeperStatValue;
    // rush_yd: SleeperStatValue;
    // fgm_yds_over_30: SleeperStatValue;
    // pass_int_td: SleeperStatValue;
    // pass_yd: SleeperStatValue;
    // pass_td: SleeperStatValue;
    // rush_td: SleeperStatValue;
    // fgmiss_0_19: SleeperStatValue;
    // def_kr_td: SleeperStatValue;
    // fum_lost: SleeperStatValue;
    // yds_allow_200_299: SleeperStatValue;
    // fgmiss_20_29: SleeperStatValue;
    // fum: SleeperStatValue;
    // safe: SleeperStatValue;
}

interface SleeperStatsResponse {
    [key: string]: SleeperStatEntries;
}

interface SleeperStatEntries {
    [key: string]: number;
}
